# Generated by Django 5.2.5 on 2026-04-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='particiapent',
            new_name='participants',
        ),
    ]
